<a href="https://colab.research.google.com/github/sailsolar/pytorch/blob/main/PT101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals

In [ ]:
import torch

In [ ]:
print(torch.__version__)


2.3.0+cu121


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
# scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [ ]:
# Vector

vector = torch.tensor([1, 2])
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [ ]:
# Matrix
MATRIX = torch.tensor([[1, 2],
                       [3, 4]])
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1,2],
                        [4,5],
                        [7,8]]])
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 2])


In [ ]:
print(TENSOR)

tensor([[[1, 2],
         [4, 5],
         [7, 8]]])


In [ ]:
TENSOR[0][2][0]

tensor(7)

### Random tensors

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
print(random_tensor.ndim) # 2
print(random_tensor.shape) # [3, 4]

2
torch.Size([3, 4])


In [ ]:
# tensor of the shape of an image
random_image_size_tensor = torch.rand(size=(3, 608, 608))
random_image_size_tensor.ndim, random_image_size_tensor.shape # 3, [608, 608, 3]

(3, torch.Size([3, 608, 608]))

### Zeroes and Ones

In [ ]:
# Tensor of all Zeroes
zeros = torch.zeros(1, 3, 4)
print(zeros)
zeros.ndim, zeros.shape

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


(3, torch.Size([1, 3, 4]))

In [ ]:
# Tensor of all Ones
ones = torch.ones(size=(4, 5))
print(ones)
ones.ndim, ones.shape
ones.dtype

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


torch.float32

### Create range of tensors and tensor-like

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# To create a tensor like something else (like method)
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

#### Biggest Errors in Deep Learning

1. Tensor not right datatype
(Precision in Computing)
2. Tensor not right shape
3. Tensor not on the right device

`device None = CPU`

`device cuda = GPU`

`required_grads = if we need PyTorch to track the gradients`

In [ ]:
flt_32_tensor = torch.tensor([1, 3, 4],
                           dtype=torch.float32,
                           device=None,
                           requires_grad=False)

# device None = CPU
# device cuda = GPU
# required_grads = if we need PyTorch to track the gradients

In [ ]:
print(flt_32_tensor.shape, flt_32_tensor.ndim)
print(flt_32_tensor.dtype)

torch.Size([3]) 1
torch.float32


In [ ]:
# Convert one tensor of specific type to another tensor of different type

flt_16_tensor = flt_32_tensor.type(torch.long)
flt_16_tensor.dtype

torch.int64

In [ ]:
flt_16_tensor * flt_32_tensor

tensor([ 1.,  9., 16.], dtype=torch.float64)

In [ ]:
int_32_tensor = torch.tensor([1, 3, 4], dtype=torch.int32, device=None, requires_grad=False)
int_32_tensor

tensor([1, 3, 4], dtype=torch.int32)

In [ ]:
int_32_tensor * flt_16_tensor

tensor([ 1.,  9., 16.], dtype=torch.float64)

### Getting information from tensors
1. how to check datatype: `tensor.dtype`
2. how to check shape: `tensor.shape`
3. how to check device: `tensor.device`

In [ ]:
print(f'Tensor datatype = {flt_16_tensor.dtype}')
print(f'Tensor shape = {flt_16_tensor.shape}')
print(f'Tensor on device = {flt_16_tensor.device}')

Tensor datatype = torch.int64
Tensor shape = torch.Size([3])
Tensor on device = cpu


### Manipulating Tensors

Tensor operations:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication


In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor / 2

tensor([0.5000, 1.0000, 1.5000])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
torch.divide(tensor, 2)

tensor([0.5000, 1.0000, 1.5000])

In [ ]:
torch.subtract(tensor, 1)

tensor([0, 1, 2])

### Matrix multiplication
1. Element-wise
2. Matrix multiplication (dot product)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 541 µs, sys: 0 ns, total: 541 µs
Wall time: 417 µs


tensor(14)

In [ ]:
tensor * tensor

tensor([1, 4, 9])

### Rules to satisfy for large scale matmul
1. The **inner dimensions** must match
2. The resulting matrix has the shape of **outer dimensions**

In [ ]:
torch.matmul(torch.rand(size=(2, 3)), torch.rand(size=(3,4))).shape

torch.Size([2, 4])

tensor([[0.0115, 0.1587, 0.3160, 0.5427],
        [0.1504, 0.7179, 0.7909, 0.2236],
        [0.3684, 0.2626, 0.1996, 0.0181]])

In [ ]:
## TRANSPOSE
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
torch.mm(tensor_A.T, tensor_B)

tensor([[ 89,  98],
        [116, 128]])

### Tensor Aggregation
min, max, mean, sum, etc.

In [ ]:
x = torch.arange(start=0, end=100, step=10)

# torch.min or x.min

In [ ]:
# Min
print(f'Min of x = {x.min()}')
# Max
print(f'Min of x = {x.max()}')
# Sum
print(f'Sum of x  = {x.sum()}')
# Mean
print(f'Mean of x = {torch.mean(x.type(torch.float32))}') # Error: Tensor is not of correct data type

Min of x = 0
Min of x = 90
Sum of x  = 450
Mean of x = 45.0


In [ ]:
### Finding positional min
x.argmin()

tensor(0)

In [ ]:
### Finding positional max
x.argmax()

tensor(9)

### Reshaping (Views), stacking (vstack, hstack), squeezing and unsquezze tensors
* Reshape - reshape tensor (has to be compatible with original size)
* View (keep same memory)
* Stacking: Vertical stack (on top of each other), hstack (side by side)
* Squeeze - remove all `1` dimensions from the target tensor
* Unsqueeze - add a `1` dimenstion to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way



In [ ]:
x = torch.arange(1, 10).type(torch.float32)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view (Share same memory as x)
z = x.view(1, 9)
z, z.shape
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Squeeze (Removes all single dimensions )
x_squeeze = torch.squeeze(x_reshaped)
x_reshaped, x_squeeze

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Unsqueeze (Add a single dimension)
x_unsqueeze = torch.unsqueeze(x_reshaped, dim=0)
x_unsqueeze

tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [ ]:
print(f'Original tensor shape: {x.shape}')
print(f'Reshaped tensor shape: {x_reshaped.shape}')
print(f'Stacked tensor shape: {x_stacked.shape}')
print(f'Squeezed reshaped_tensor shape: {x_squeeze.shape}')
print(f'Unsqueezed reshaped_tensor shape: {x_unsqueeze.shape}')

Original tensor shape: torch.Size([9])
Reshaped tensor shape: torch.Size([1, 9])
Stacked tensor shape: torch.Size([9, 4])
Squeezed reshaped_tensor shape: torch.Size([9])
Unsqueezed reshaped_tensor shape: torch.Size([1, 1, 9])


In [ ]:
# Permute (rearrange dimensions in a specified format)
x_original = torch.rand(size=(224, 224, 3))
x_permuted = torch.permute(x_original, (2, 0, 1))

In [ ]:
print(f'Tensor shape before permute: {x_original.shape}')
print(f'Tensor shape after permute: {x_permuted.shape}')

Tensor shape before permute: torch.Size([224, 224, 3])
Tensor shape after permute: torch.Size([3, 224, 224])


### Indexing (selecting data from Tensors)

Indexing in PyTorch is same as NumPy

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)

In [ ]:
# Indexing on the most outer bracket/dim
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Indexing on the middle bracket/dim
x[0][1]

tensor([4, 5, 6])

In [ ]:
# Indexing on the inner most dimension/bracket
x[0][2][2]

torch.Size([])

In [ ]:
# Use : to get all of the target dimension
x[:, 1, 2]

tensor([6])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of the 2nd dimension
x[:, :, 2]

tensor([[3, 6, 9]])

In [ ]:
# Get all of 0 dim but only 1 index value of 1st and 2nd dimension
x[:, 1, 1]

torch.Size([1])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

### PyTorch tensor & NumPy
 * NumPy -> PyTorch

 `torch.from_numpy(ndarray)`
 * PyTorch -> NumPy

 `torch.Tensor.numpy()`

In [ ]:
import torch
import numpy as np

# from numPy to pyTorch
array = np.arange(1., 8.)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = tensor.type(torch.float32)

In [ ]:
# From PyTorch to NumPy

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

### Reproducibility

Random seed concept

In [ ]:
import torch

MSEED = 42
torch.manual_seed(MSEED)
tensor_A = torch.rand(3, 4)

torch.manual_seed(MSEED)
tensor_B = torch.rand(3, 4)

print(tensor_A == tensor_B)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running Tensors and PT Objects on GPU

### Getting a GPU
1. Colab Free Tier
2. Use personal GPU
3. Use cloud computing (AWS, GCP, Azure)


In [ ]:
!nvidia-smi

Tue May 28 09:49:26 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
# Checking for GPU access with PT
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else 'cpu'

In [ ]:
# Count no. of GPU
torch.cuda.device_count()

1

### Moving tensors to GPU

In [ ]:
tensor = torch.tensor([1,2,3], device='cpu', requires_grad=False)

In [ ]:
tensor, tensor.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
## Move tensor back to the CPU
tensor_on_cpu = tensor_on_gpu.cpu()

In [ ]:
tensor_on_cpu.numpy()

array([1, 2, 3])